Add multi geometry types
claeis/umleditor pull request #75
Opened 2023-10-18 09:15 UTC by domi-b

References https://github.com/claeis/umleditor/issues/63

2023-10-23 06:44 UTC, patrickackermann commented on resources/de/ch/ehi/umleditor/application/resources/IliBaseTypeKind_de.properties
> +CITime=Zeit
Q: Was hat sich auf den Zeilen ohne offensichtilche Änderung geändert?

2023-10-23 06:44 UTC, patrickackermann commented on src/ch/ehi/umleditor/application/AttributeDefDialog.java
> +		getPnlTypeCoord().setMulti(false);
PP: Muss _isMulti_ explizit noch auf _false_ gesetzt werden? Bei POLYLINE, SURFACE und AREA wird es nicht explizit gesetzt?

2023-10-23 08:08 UTC, domi-b commented on resources/de/ch/ehi/umleditor/application/resources/IliBaseTypeKind_de.properties
> +CITime=Zeit
Diese Datei hatte inkonsistente line feeds (LF / CRLF) und ich habe die Multi-Varianten hinzugefügt, deshalb wurde es automatisch angepasst.

2023-10-23 08:10 UTC, domi-b commented on src/ch/ehi/umleditor/application/AttributeDefDialog.java
> +		getPnlTypeCoord().setMulti(false);
Bei COORD wird das Panel mit _null_ initialisiert, deshalb muss es explizit gesetzt werden. Bei den anderen Typen kann es isMulti() aus dem Objekt übernehmen, welches den Default-Wert _false_ hat.

2023-10-23 08:30 UTC, patrickackermann approved these changes

2023-11-29 08:40 UTC, claeis requested changes

2023-11-29 08:40 UTC, claeis commented on src/ch/ehi/interlis/domainsandconstants/linetypes/LineType.java
> +                public void setMulti(boolean isMulti) {
richtig wäre:

    if(isMulti != value1){
      isMulti= value1;
      ch.ehi.uml1_4.changepropagation.MetaModel.getInstance().notifyChange(new ch.ehi.uml1_4.changepropagation.MetaModelChange(this,"setMulti"));
    }

2023-11-29 08:40 UTC, claeis commented on src/ch/ehi/interlis/domainsandconstants/basetypes/CoordinateType.java
> +                public void setMulti(boolean isMulti) {
richtig wäre:

    if(isMulti != value1){
      isMulti= value1;
      ch.ehi.uml1_4.changepropagation.MetaModel.getInstance().notifyChange(new ch.ehi.uml1_4.changepropagation.MetaModelChange(this,"setMulti"));
    }

2023-11-29 08:40 UTC, claeis commented on src/ch/ehi/interlis/domainsandconstants/basetypes/CoordinateType.java
> +                public String getIliTypeName() {
Funktion gehört nicht hier hin, weil so kennt diese Klasse die ili-Syntax, das ist aber nicht ihre Aufgabe. Ihre Aufgabe ist, den Typ zu repräsentieren. TransferFromUmlMetamodel kennt die Syntax.

2023-11-29 08:40 UTC, claeis commented on src/ch/ehi/interlis/domainsandconstants/linetypes/LineType.java
> +                public abstract String getIliTypeName();
Funktion gehört nicht hier hin, weil so kennt diese Klasse die ili-Syntax, das ist aber nicht ihre Aufgabe. Ihre Aufgabe ist, den Typ zu repräsentieren. TransferFromUmlMetamodel kennt die Syntax.

2023-11-29 08:40 UTC, claeis commented on src/ch/ehi/umleditor/interlis/iliexport/TransferFromUmlMetamodel.java
> +      out.write(type.getIliTypeName());
hier lösen z.B. type.isMulti()? "MULTICOORD":"COORD". (type darf die Syntax nicht kennen). Analog mit den anderen MULTI Typen

2023-11-30 08:51 UTC, merged